language: r
cache: packages

warnings_are_errors: false

r_github_packages:
  - jimhester/covr

r_binary_packages:
  - testthat
  - ggplot2
  - RColorBrewer
  - viridis 

after_success:
  - Rscript -e 'covr::codecov()'
  - Rscript -e 'covr::coveralls()'

